FORMAT: 1A
HOST: http://check2budget.apiblueprint.org/

# check2budget

Check 2 Budget is an api for handling simple household budgets
## Group Bank

Resources related to banks in the API.

## Banks [/banks/{bank_id}]

A Bank object has the following attributes:

+ name

+ Parameters
    + bank_id (required, number, `1`) ... I+ Request (application/json)

+ Response 200 (application/json)

    + Body

            {
                "errors": false,
                "name": "test bank"
            }