## Group Banks

Resources related to banks in the API.

## Banks Collection [/banks]

A Bank object has the following attributes:

+ id
+ name
+ description
+ schedule
+ created_by

### Retrieve all Banks [GET]

+ Response 200 (application/json)

    + Body

            {
                "errors": false,
                "banks" : [
                    {
                        "id" : 1,
                        "name": "test bank",
                        "description" : "something about this bank",
                        "schedule" :[
                            {
                                "id" : 1,
                                "name" : "Every 2 Weeks"
                            }
                        ],
                        "created_by" :[
                            {
                                "id" : 1,
                                "domainname" : "hilsonhouse"
                            }
                        ]
                    },
                    {
                        "id" : 2,
                        "name": "test bank 2",
                        "description" : "something about this bank",
                        "schedule" :[
                            {
                                "id" : 1,
                                "name" : "Every 2 Weeks"
                            }
                        ],
                        "domain" :[
                            {
                                "id" : 1,
                                "domainname" : "hilsonhouse"
                            }
                        ]
                    }
                ]
            }

### Create a Bank [POST]

+ Request (application/json)

    + Body

            {
                "name": "test bank",
                "description": "something about this bank",
                "schedule" : 1,
                "_token": "generated-token"
            }

+ Response 200 (application/json)

    + Body

            {
                "errors": false,
                "details": "You have successfully created a bank!"
            }

## Bank [/banks/{id}]

+ Parameters
    + id (required, number, `1`) ... ID of the Bank in form of an integer

### Retrieve a bank [GET]

+ Response 200 (application/json)

    + Body

            {
                "errors" : false,
                "banks" : [
                    {
                        "id" : 1,
                        "name": "test bank",
                        "description" : "something about this bank",
                        "schedule" :[
                            {
                                "id" : 1,
                                "name" : "Every 2 Weeks"
                            }
                        ],
                        "domain" :[
                            {
                                "id" : 1,
                                "domainname" : "hilsonhouse"
                            }
                        ]
                    }
                ]
            }

### Edit a Bank [POST]

+ Request (application/json)

    + Body

            {
                "name": "test bank",
                "description": "something about this bank",
                "schedule" : 1,
                "_token": "generated-token"
            }

+ Response 200 (application/json)

    + Body

            {
                "errors": false,
                "details": "You have successfully edited a bank!"
            }

### Delete a Bank [DELETE]

+ Response 200 (application/json)

        {
            "errors" : false,
            "details" : "You have successfully deleted a bank!"
        }


## Banks By User [/banks/user/{id}]

+ Parameters
    + id (required, number, `1`) ... id of the User in form of an integer

### Retrieve banks by user [GET]

+ Response 200 (application/json)

    + Body

            {
                "errors" : false,
                "banks" : [
                    {
                        "id" : 1,
                        "name": "test bank",
                        "description" : "something about this bank",
                        "schedule" :[
                            {
                                "id" : 1,
                                "name" : "Every 2 Weeks"
                            }
                        ],
                        "domain" :[
                            {
                                "id" : 1,
                                "domainname" : "hilsonhouse"
                            }
                        ]
                    },
                    {
                        "id" : 2,
                        "name": "test bank 2",
                        "description" : "something about this bank",
                        "schedule" :[
                            {
                                "id" : 1,
                                "name" : "Every 2 Weeks"
                            }
                        ],
                        "domain" :[
                            {
                                "id" : 1,
                                "domainname" : "hilsonhouse"
                            }
                        ]
                    }
                ]
            }
